server:
  address: "server:12345"
loop:
  amount: 1
  period: "1s"
log:
  level: "DEBUG"
batch:
  maxAmount: 10

bet:
  name: "gyro"
  surname: "zeppelli"
  dni: "12345678"
  birthdate: "1886-08-24"
  number: "4815162342"

agency: 1