
name: tp0
services:


  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    volumes:
      - type: bind
        source: ./server/config.ini
        target: /config.ini

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - CLI_BET_NAME=gyro
      - CLI_BET_SURNAME=zeppelli
      - CLI_BET_DNI=12345678
      - CLI_BET_BIRTHDATE=1886-08-24
      - CLI_BET_NUMBER=4815162342
      - CLI_AGENCY=1
    
    volumes:
      - type: bind
        source: ./client/config.yaml
        target: /config.yaml
      - type: bind
        source: ./.data/agency-1.csv
        target: /agency-1.csv
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

