echo "Starting health-check"

if [ "$(echo "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" | nc -w 20 server 12345)" = "ping" ]; then
    exit 0
fi
exit 1
